module.exports = Object.freeze({
    ALIGNMENTS: {
        "unaligned": ["U"],
        "any": ["A"],
        "good": ["G"],
        "evil": ["E"],
        "lawful": ["L"],
        "chaotic": ["C"],
        "neutral": ["N"],
        "lawful good": ["L","G"],
        "neutral good": ["N", "G"],
        "chaotic good": ["C","G"],
        "lawful neutral": ["L","N"],
        "chaotic neutral": ["C","N"],
        "lawful evil": ["L","E"],
        "neutral evil": ["N","E"],
        "chaotic evil": ["C","E"],
        "any neutral": ["NX","NY","N"],
        "any lawful": ["L","G","NY","E"],
        "any chaotic": ["C","G","NY","E"],
        "any good": ["G","L","NX","C"],
        "any evil": ["E","L","NX","C"],
        "any non-lawful": ["NX","C","G","NY","E"],
        "any non-chaotic": ["L","NX","G","NY","E"],
        "any non-good": ["L","NX","C","NY","E"],
        "any non-evil": ["L","NX","C","G","NY"]
    },
    DAMAGE_TYPES: [
        "acid",
        "bludgeoning",
        "cold",
        "fire",
        "force",
        "lightning",
        "necrotic",
        "piercing",
        "poison",
        "psychic",
        "slashing",
        "radiant",
        "thunder"
    ]
});